### ISSUE TITLE
Archinstall cannot install to nvme

### ISSUE THREAD

**Issue by walksanatora** [archlinux/archinstall#1613]
I have a nvme drive (nvmen0)
But arch install does not detect it

**Comment by walksanatora** [comment]
Nvm it worked after I fixed it manually

**Comment by TuxMC-sys** [comment]
Remember to close the issue

**Comment by marek-lach** [comment]
> Remember to close the issue

I also have the same issue and didnt fix it yet. The error reads: _Not a block device._ Whatever that means...

**Comment by walksanatora** [comment]
mabey try just re-creating the partition table on the device
