### ISSUE TITLE
archinstall, hyprland error - Unable to start service SeatAccess.polkit

### ISSUE THREAD

**Issue by Johnson1255** [archlinux/archinstall#2908]
### Which ISO version are you using?

archlinux-2024.11.01-x86_64.iso

### The installation log

```json
https://0x0.st/Xnd2.log
```

### describe the problem

While trying to install Hyprland using archinstall, I encountered the same issue described in [[3.0] Unable to start service SeatAccess.polkit / SeatAccess.seatd](https://github.com/archlinux/archinstall/issues/2866) I've attempted several solutions mentioned in that thread.

While investigating the issue, I noticed a potentially relevant code change in the commits. A fix that used .value was previously added and then later removed:

```
return [pref.value]
return [pref]
```

I'm not certain if this change is related to the issue, but I'm still unable to successfully install Hyprland through archinstall. The installation fails with SeatAccess-related errors.

**Comment by svartkanin** [comment]
This has been fixed already

**Comment by yebei199** [comment]
> This has been fixed already

But I still encounter this bug in version 3.0.10 using the archlinux-2025.09.01-x86_64.iso.
