### ISSUE TITLE
pipewire-jack-1:1.4.7-1 and jack2-1.9.22-1 are in conflict

### ISSUE THREAD

**Issue by word-sys** [archlinux/archinstall#3705]
### Which ISO version are you using?

2025-08-1

### The installation log

```json
[2025-08-03 10:31:06] - DEBUG - Installing audio server: pipewire
[2025-08-03 10:31:06] - INFO - Installing packages: ['sof-firmware']
[2025-08-03 10:31:27] - INFO - Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber']
[2025-08-03 10:31:28] - ERROR - Could not strap in packages: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt', 'pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber', '--noconfirm'] exited with abnormal exit code [1]: ate[K[2E multilib is up to date[K[1Ewarning: libpulse-17.0+r43+g3e2bb8a1e-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
:: pipewire-jack-1:1.4.7-1 and jack2-1.9.22-1 are in conflict (jack). Remove jack2? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: pipewire-jack-1:1.4.7-1 and jack2-1.9.22-1 are in conflict
[?25h==> ERROR: Failed to install packages to new root

[2025-08-03 10:34:04] - ERROR - Pacstrap failed. See /var/log/archinstall/install.log or above message for error details: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt', 'pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber', '--noconfirm'] exited with abnormal exit code [1]: ate[K[2E multilib is up to date[K[1Ewarning: libpulse-17.0+r43+g3e2bb8a1e-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
:: pipewire-jack-1:1.4.7-1 and jack2-1.9.22-1 are in conflict (jack). Remove jack2? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: pipewire-jack-1:1.4.7-1 and jack2-1.9.22-1 are in conflict
[?25h==> ERROR: Failed to install packages to new root

[2025-08-03 10:34:04] - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/archinstall/lib/pacman/__init__.py", line 45, in ask
    func(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/archinstall/lib/general.py", line 326, in __init__
    self.create_session()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/archinstall/lib/general.py", line 366, in create_session
    with SysCommandWorker(
         ~~~~~~~~~~~~~~~~^
    	self.cmd,
     ^^^^^^^^^
    ...<3 lines>...
    	working_directory=self.working_directory,
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as session:
    ^
  File "/usr/lib/python3.13/site-packages/archinstall/lib/general.py", line 194, in __exit__
    raise SysCallError(
    ...<3 lines>...
    )
archinstall.lib.exceptions.SysCallError: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt', 'pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber', '--noconfirm'] exited with abnormal exit code [1]: ate[K[2E multilib is up to date[K[1Ewarning: libpulse-17.0+r43+g3e2bb8a1e-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
:: pipewire-jack-1:1.4.7-1 and jack2-1.9.22-1 are in conflict (jack). Remove jack2? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: pipewire-jack-1:1.4.7-1 and jack2-1.9.22-1 are in conflict
[?25h==> ERROR: Failed to install packages to new root


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/archinstall/__init__.py", line 104, in run_as_a_module
    rc = main()
  File "/usr/lib/python3.13/site-packages/archinstall/__init__.py", line 94, in main
    importlib.import_module(mod_name)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.13/site-packages/archinstall/scripts/guided.py", line 212, in <module>
    guided()
    ~~~~~~^^
  File "/usr/lib/python3.13/site-packages/archinstall/scripts/guided.py", line 209, in guided
    perform_installation(arch_config_handler.args.mountpoint)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/archinstall/scripts/guided.py", line 127, in perform_installation
    application_handler.install_applications(installation, app_config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/archinstall/lib/applications/application_handler.py", line 21, in install_applications
    AudioApp().install(
    ~~~~~~~~~~~~~~~~~~^
    	install_session,
     ^^^^^^^^^^^^^^^^
    	app_config.audio_config,
     ^^^^^^^^^^^^^^^^^^^^^^^^
    	users,
     ^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/archinstall/applications/audio.py", line 77, in install
    install_session.add_additional_packages(self.pipewire_packages)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/archinstall/lib/installer.py", line 1628, in add_additional_packages
    return self.pacman.strap(packages)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/archinstall/lib/pacman/__init__.py", line 77, in strap
    self.ask(
    ~~~~~~~~^
    	'Could not strap in packages',
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    	peek_output=True,
     ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/archinstall/lib/pacman/__init__.py", line 51, in ask
    raise RequirementError(f'{bail_message}: {err}')
archinstall.lib.exceptions.RequirementError: Pacstrap failed. See /var/log/archinstall/install.log or above message for error details: ['/usr/bin/pacstrap', '-C', '/etc/pacman.conf', '-K', '/mnt', 'pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber', '--noconfirm'] exited with abnormal exit code [1]: ate[K[2E multilib is up to date[K[1Ewarning: libpulse-17.0+r43+g3e2bb8a1e-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
:: pipewire-jack-1:1.4.7-1 and jack2-1.9.22-1 are in conflict (jack). Remove jack2? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: pipewire-jack-1:1.4.7-1 and jack2-1.9.22-1 are in conflict
[?25h==> ERROR: Failed to install packages to new root


[2025-08-03 10:34:04] - WARNING - Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

#### Description of the issue
classic Archlinux installation, im using pipewire for sound, when archinstall tries to install pipewire:
pipewire-jack-1:1.4.7-1 and jack2-1.9.22-1 are in conflict
i cannot continue after that, it just stuck
EDIT: I added screenshot and install.log so you can look full install.log because github doesnt let me add more than 65000 characters somehow idk

[install.log](https://github.com/user-attachments/files/21565544/install.log)

![Image](https://github.com/user-attachments/assets/28c29618-060a-40fc-a24d-9c2a3599a1fd)

**Comment by word-sys** [comment]
Added install.log and screenshot, you can look full install.log, github didnt let me add more than 65000 charachters to install.log place on creating issue

**Comment by Torxed** [comment]
Weird, I'll have to take a deeper look then.
Thought we solved this before releasing 3.0.9 :/

**Comment by word-sys** [comment]
I fixed this issue FOR ME by using 2025-07-01 ISO with stock archinstall which came with it which is 3.0.8-1, i set up my system like that right now :)

**Comment by Torxed** [comment]
Strange, we fixed it because 3.0.8 had the bug.. hmm..

**Comment by Torxed** [comment]
We also have users reporting [that it works](https://discord.com/channels/726808923662712894/726809631342592081/1401730115750072391) but we also have users reporting that it's still broken. So we'll keeping looking in to this.

<img width="434" height="141" alt="Image" src="https://github.com/user-attachments/assets/08e3e189-88a3-48ef-b96d-1139940fab5e" />

**Comment by EK-92** [comment]
heh, awkward moment when your discord comment gets on github before you do

it's real, to replicate:
- select pipewire as sound server
- select firefox as addition package
<img width="1280" height="960" alt="Image" src="https://github.com/user-attachments/assets/9fb6af17-872e-4130-990b-32f19b5f386e" />

here's my thinking: if we put additional packages after the sound setup, it _should_ (?) detect `jack` provided by already installed `pipewire-jack` and not pull `jack2` package

**Comment by Torxed** [comment]
Confirmed that this should now be fixed thanks to #3709, so I'll close this.
I tried by installing `firefox` with `pipewire` and `KDE Plasma`. And the issue appears to be gone.

**Comment by thekayrasari** [comment]
Tried just now on my laptop with additional packages: git+firefox+hyprland desktop. Issue still exists.

**Comment by EK-92** [comment]
> Tried just now on my laptop with additional packages: git+firefox+hyprland desktop. Issue still exists.

Yea in this repo "master" branch is basically "dev", so until enough pull requests piles up there's no new release and it could be a few weeks in between those. I'm not sure how you can test against "master" branch even, other than cloning repo after booting live arch env. Afaik the main issue is cloud storage restrictions, having to generate a >1Gb ISO file for each fix.

@Torxed maybe issues should stay open until new release? With like a label `awaiting release` or `[SOLVED]` in title or something. Otherwise it's kinda confusing when it's `Closed` but still happening with current release.

**Comment by thekayrasari** [comment]
> > Tried just now on my laptop with additional packages: git+firefox+hyprland desktop. Issue still exists.
> 
> Yea in this repo "master" branch is basically "dev", so until enough pull requests piles up there's no new release and it could be a few weeks in between those. I'm not sure how you can test against "master" branch even, other than cloning repo after booting live arch env. Afaik the main issue is cloud storage restrictions, having to generate a >1Gb ISO file for each fix.
> 
> [@Torxed](https://github.com/Torxed) maybe issues should stay open until new release? With like a label `awaiting release` or `[SOLVED]` in title or something. Otherwise it's kinda confusing when it's `Closed` but still happening with current release.

I'm aware, just seconding, thank you.

**Comment by XcOM987** [comment]
This is still an issue as of this week, I just had the same bug, using 2025.08.01 iso, pipewire, firefox, and bitwarden, replicated the issue, removing the additional packages allows the install to complete, conflict isn't present following booting in to the installed environment

**Comment by tilda** [comment]
FTR: was able to consistently work around this by adding `pipewire-jack` to additional packages on current archinstall 3.0.9/archiso 2025.08.01
